// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'table_preview_provider.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, type=warning
/// Runs `SELECT * FROM "schema"."table" LIMIT 100` through the active adapter.
///
/// All SQL is generated by the adapter (quoting + LIMIT) so it stays
/// engine-correct and lives behind the driver-agnostic contract.

@ProviderFor(tablePreview)
final tablePreviewProvider = TablePreviewFamily._();

/// Runs `SELECT * FROM "schema"."table" LIMIT 100` through the active adapter.
///
/// All SQL is generated by the adapter (quoting + LIMIT) so it stays
/// engine-correct and lives behind the driver-agnostic contract.

final class TablePreviewProvider
    extends
        $FunctionalProvider<
          AsyncValue<QueryResult>,
          QueryResult,
          FutureOr<QueryResult>
        >
    with $FutureModifier<QueryResult>, $FutureProvider<QueryResult> {
  /// Runs `SELECT * FROM "schema"."table" LIMIT 100` through the active adapter.
  ///
  /// All SQL is generated by the adapter (quoting + LIMIT) so it stays
  /// engine-correct and lives behind the driver-agnostic contract.
  TablePreviewProvider._({
    required TablePreviewFamily super.from,
    required (String, String) super.argument,
  }) : super(
         retry: null,
         name: r'tablePreviewProvider',
         isAutoDispose: true,
         dependencies: null,
         $allTransitiveDependencies: null,
       );

  @override
  String debugGetCreateSourceHash() => _$tablePreviewHash();

  @override
  String toString() {
    return r'tablePreviewProvider'
        ''
        '$argument';
  }

  @$internal
  @override
  $FutureProviderElement<QueryResult> $createElement(
    $ProviderPointer pointer,
  ) => $FutureProviderElement(pointer);

  @override
  FutureOr<QueryResult> create(Ref ref) {
    final argument = this.argument as (String, String);
    return tablePreview(ref, argument.$1, argument.$2);
  }

  @override
  bool operator ==(Object other) {
    return other is TablePreviewProvider && other.argument == argument;
  }

  @override
  int get hashCode {
    return argument.hashCode;
  }
}

String _$tablePreviewHash() => r'5cae51dbd69ff252a2355bcd8e5f9b420c1e763a';

/// Runs `SELECT * FROM "schema"."table" LIMIT 100` through the active adapter.
///
/// All SQL is generated by the adapter (quoting + LIMIT) so it stays
/// engine-correct and lives behind the driver-agnostic contract.

final class TablePreviewFamily extends $Family
    with $FunctionalFamilyOverride<FutureOr<QueryResult>, (String, String)> {
  TablePreviewFamily._()
    : super(
        retry: null,
        name: r'tablePreviewProvider',
        dependencies: null,
        $allTransitiveDependencies: null,
        isAutoDispose: true,
      );

  /// Runs `SELECT * FROM "schema"."table" LIMIT 100` through the active adapter.
  ///
  /// All SQL is generated by the adapter (quoting + LIMIT) so it stays
  /// engine-correct and lives behind the driver-agnostic contract.

  TablePreviewProvider call(String schema, String table) =>
      TablePreviewProvider._(argument: (schema, table), from: this);

  @override
  String toString() => r'tablePreviewProvider';
}
