import 'package:juno/db/adapter/models/query_result.dart';
import 'package:juno/features/connections/application/active_connection_provider.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'table_preview_provider.g.dart';

/// How many rows a table preview fetches. The LIMIT does the work — previewing
/// a million-row table stays cheap (plan §7 Phase 4).
const int tablePreviewLimit = 100;

/// Runs `SELECT * FROM "schema"."table" LIMIT 100` through the active adapter.
///
/// All SQL is generated by the adapter (quoting + LIMIT) so it stays
/// engine-correct and lives behind the driver-agnostic contract.
@riverpod
Future<QueryResult> tablePreview(Ref ref, String schema, String table) {
  final adapter = ref.watch(activeAdapterProvider);
  final sql =
      'SELECT * FROM ${adapter.quoteIdentifier(schema)}'
      '.${adapter.quoteIdentifier(table)} '
      '${adapter.limitClause(tablePreviewLimit, 0)}';
  return adapter.execute(sql);
}
